Fix bug in using the --authorized-keys-urls argument
This was the error:
    Traceback (most recent call last):
      File "/home/mike/vcs/cyber/bootstrap2020/debian-11-main.py", line 135, in <module>
        f.write(url.encode())
    AttributeError: 'URL' object has no attribute 'encode'

Argparse doesn't put any of the 'default' options through the type checker.
This caused unpredictability in what object type that option will have
since the defaults were all strings not URL objects.