(BROKEN) build GTK without screenshot functions
Just removing the .h and not even the .c is breaking the ability to link the .so.
We actually would be happy just building the .typelib file.
But working out how to build ONLY that requires understanding meson, and RIGHT NOW, I don't!

Here's the build transcript:

    ⋮
    dpkg-source: info: using source format '3.0 (quilt)'
    dpkg-source: info: building gdk-pixbuf using existing ./gdk-pixbuf_2.42.2+dfsg.orig.tar.xz
    dpkg-source: info: using patch list from debian/patches/series
    dpkg-source: info: local changes detected, the modified files are:
     gdk-pixbuf-2.42.2+dfsg/gdk-pixbuf/gdk-pixbuf-core.h
    dpkg-source: info: local changes have been recorded in a new patch: gdk-pixbuf-2.42.2+dfsg/debian/patches/debian-changes-2.42.2+dfsg-1PrisonPC1
    dpkg-source: info: building gdk-pixbuf in gdk-pixbuf_2.42.2+dfsg-1PrisonPC1.debian.tar.xz
    dpkg-source: info: building gdk-pixbuf in gdk-pixbuf_2.42.2+dfsg-1PrisonPC1.dsc
     dpkg-buildpackage -us -uc -ui -tc -j8
    dpkg-buildpackage: info: source package gdk-pixbuf
    dpkg-buildpackage: info: source version 2.42.2+dfsg-1PrisonPC1
    dpkg-buildpackage: info: source distribution bullseye
    dpkg-buildpackage: info: source changed by Trent W. Buck <twb@cyber.com.au>
     dpkg-source --before-build .
    dpkg-buildpackage: info: host architecture amd64
     debian/rules clean
    dh clean --with gir,gnome
    make[1]: Entering directory '/gdk-pixbuf-2.42.2+dfsg'
    dh_clean
    set -e; for file in libgdk-pixbuf-2.0-0.triggers libgdk-pixbuf-2.0-0.postinst libgdk-pixbuf-2.0-0.postrm; do \
            rm -f debian/$file; \
    done
    rm -rf debian/build-mime
    make[1]: Leaving directory '/gdk-pixbuf-2.42.2+dfsg'
     dpkg-source -b .
    dpkg-source: info: using source format '3.0 (quilt)'
    dpkg-source: info: building gdk-pixbuf using existing ./gdk-pixbuf_2.42.2+dfsg.orig.tar.xz
    dpkg-source: info: using patch list from debian/patches/series
    dpkg-source: info: building gdk-pixbuf in gdk-pixbuf_2.42.2+dfsg-1PrisonPC1.debian.tar.xz
    dpkg-source: info: building gdk-pixbuf in gdk-pixbuf_2.42.2+dfsg-1PrisonPC1.dsc
     debian/rules binary
    dh binary --with gir,gnome
    make[1]: Entering directory '/gdk-pixbuf-2.42.2+dfsg'
    dh_auto_configure -- \
            -Dgtk_doc=true \
            -Dinstalled_tests=true \
            -Dintrospection=enabled \

    The Meson build system
    Version: 0.56.2
    Source dir: /gdk-pixbuf-2.42.2+dfsg
    Build dir: /gdk-pixbuf-2.42.2+dfsg/obj-x86_64-linux-gnu
    Build type: native build
    Project name: gdk-pixbuf
    Project version: 2.42.2
    Using 'CFLAGS' from environment with value: '-g -O2 -ffile-prefix-map=/gdk-pixbuf-2.42.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security'
    Using 'LDFLAGS' from environment with value: '-Wl,-z,relro -Wl,-z,now -Wl,-O1 -Wl,-z,defs -Wl,--as-needed'
    Using 'CPPFLAGS' from environment with value: '-Wdate-time -D_FORTIFY_SOURCE=2'
    C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
    C linker for the host machine: cc ld.bfd 2.35.2
    Using 'CFLAGS' from environment with value: '-g -O2 -ffile-prefix-map=/gdk-pixbuf-2.42.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security'
    Using 'LDFLAGS' from environment with value: '-Wl,-z,relro -Wl,-z,now -Wl,-O1 -Wl,-z,defs -Wl,--as-needed'
    Using 'CPPFLAGS' from environment with value: '-Wdate-time -D_FORTIFY_SOURCE=2'
    Host machine cpu family: x86_64
    Host machine cpu: x86_64
    Found pkg-config: /usr/bin/pkg-config (0.29.2)
    Run-time dependency glib-2.0 found: YES 2.66.8
    Run-time dependency gobject-2.0 found: YES 2.66.8
    Run-time dependency gmodule-no-export-2.0 found: YES 2.66.8
    Run-time dependency gio-2.0 found: YES 2.66.8
    Has header "unistd.h" : YES
    Has header "sys/resource.h" : YES
    Has header "sys/time.h" : YES
    Library m found: YES
    Checking for function "round" with dependency -lm: YES
    Checking for function "lrint" with dependency -lm: YES
    Checking for function "bind_textdomain_codeset" : YES
    Checking for function "setrlimit" : YES
    Checking if "sigsetjmp" links: YES
    Compiler for C supports arguments -Wpointer-arith: YES
    Compiler for C supports arguments -Wformat=2: YES
    Compiler for C supports arguments -Wstrict-prototypes: YES
    Compiler for C supports arguments -Wnested-externs: YES
    Compiler for C supports arguments -Wold-style-definition: YES
    Compiler for C supports arguments -Wdeclaration-after-statement: YES
    Compiler for C supports arguments -Wunused: YES
    Compiler for C supports arguments -Wcast-align: YES
    Compiler for C supports arguments -Wmissing-noreturn: YES
    Compiler for C supports arguments -Wmissing-format-attribute: YES
    Compiler for C supports arguments -Wlogical-op: YES
    Compiler for C supports arguments -fno-strict-aliasing: YES
    Compiler for C supports arguments -Wno-int-conversion: YES
    Compiler for C supports arguments -Wno-uninitialized: YES
    Compiler for C supports arguments -Wno-discarded-qualifiers: YES
    Compiler for C supports arguments -Werror=implicit: YES
    Compiler for C supports arguments -Werror=nonnull: YES
    Compiler for C supports arguments -Werror=init-self: YES
    Compiler for C supports arguments -Werror=main: YES
    Compiler for C supports arguments -Werror=missing-braces: YES
    Compiler for C supports arguments -Werror=sequence-point: YES
    Compiler for C supports arguments -Werror=return-type: YES
    Compiler for C supports arguments -Werror=trigraphs: YES
    Compiler for C supports arguments -Werror=array-bounds: YES
    Compiler for C supports arguments -Werror=write-strings: YES
    Compiler for C supports arguments -Werror=address: YES
    Compiler for C supports arguments -Werror=int-to-pointer-cast: YES
    Compiler for C supports arguments -Werror=pointer-to-int-cast: YES
    Compiler for C supports arguments -Werror=empty-body: YES
    Compiler for C supports arguments -fvisibility=hidden: YES
    Compiler for C supports link arguments -Wl,-Bsymbolic: YES
    Compiler for C supports link arguments -Wl,-z,relro: YES
    Compiler for C supports link arguments -Wl,-z,now: YES
    Run-time dependency shared-mime-info found: YES 2.0
    Library mlib found: NO
    Run-time dependency libpng16 found: YES 1.6.37
    Has header "jpeglib.h" : YES
    Library jpeg found: YES
    Checking for function "jpeg_destroy_decompress" with dependency -ljpeg: YES
    Checking for function "jpeg_simple_progression" with dependency -ljpeg: YES
    Run-time dependency libtiff-4 found: YES 4.2.0
    Configuring config.h using configuration
    Program build-aux/gen-resources.py found: YES (/usr/bin/python3 /gdk-pixbuf-2.42.2+dfsg/build-aux/gen-resources.py)
    Program build-aux/gen-installed-test.py found: YES (/usr/bin/python3 /gdk-pixbuf-2.42.2+dfsg/build-aux/gen-installed-test.py)
    Program build-aux/gen-thumbnailer.py found: YES (/usr/bin/python3 /gdk-pixbuf-2.42.2+dfsg/build-aux/gen-thumbnailer.py)
    Configuring gdk-pixbuf-features.h using configuration
    Found pkg-config: /usr/bin/pkg-config (0.29.2)
    Program glib-genmarshal found: YES (/usr/bin/glib-genmarshal)
    Program glib-mkenums found: YES (/usr/bin/glib-mkenums)
    Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
    Build-time dependency gobject-introspection-1.0 found: YES 1.66.1
    Program g_ir_scanner found: YES (/usr/bin/g-ir-scanner)
    Program g_ir_compiler found: YES (/usr/bin/g-ir-compiler)
    Configuring version.xml using configuration
    Program gtkdoc-scan found: YES (/usr/bin/gtkdoc-scan)
    Program gtkdoc-scangobj found: YES (/usr/bin/gtkdoc-scangobj)
    Program gtkdoc-mkdb found: YES (/usr/bin/gtkdoc-mkdb)
    Program gtkdoc-mkhtml found: YES (/usr/bin/gtkdoc-mkhtml)
    Program gtkdoc-fixxref found: YES (/usr/bin/gtkdoc-fixxref)
    Program xsltproc found: YES (/usr/bin/xsltproc)
    Program build-aux/post-install.sh found: YES (/bin/sh /gdk-pixbuf-2.42.2+dfsg/build-aux/post-install.sh)
    Message:
    GDK-Pixbuf 2.42.2
    ==================
               prefix: /usr
               libdir: /usr/lib/x86_64-linux-gnu
              datadir: /usr/share
           libexecdir: /usr/libexec

      enabled loaders: png jpeg tiff

        documentation: true
            man pages: true
        introspection: true
      installed tests: true
          relocatable: false

    Build targets in project: 87

    Option buildtype is: plain [default: debugoptimized]
    Found ninja-1.10.1 at /usr/bin/ninja
    make[1]: Leaving directory '/gdk-pixbuf-2.42.2+dfsg'
    [1/171] Generating pixbuf-construction.test with a custom command
    [2/171] Generating animation.test with a custom command
    [3/171] Generating cve-2015-4491.test with a custom command
    [4/171] Generating gdk-pixbuf-marshal_c with a custom command
    INFO: Reading ../gdk-pixbuf/gdk-pixbuf-marshal.list...
    [5/171] Generating gdk-pixbuf-marshal_h with a custom command
    INFO: Reading ../gdk-pixbuf/gdk-pixbuf-marshal.list...
    [6/171] Generating pixbuf-fail.test with a custom command
    [7/171] Generating pixbuf-icon-serialize.test with a custom command
    [8/171] Generating pixbuf-randomly-modified.test with a custom command
    [9/171] Generating pixbuf-gif.test with a custom command
    [10/171] Generating pixbuf-threads.test with a custom command
    [11/171] Generating pixbuf-icc.test with a custom command
    [12/171] Generating pixbuf-jpeg.test with a custom command
    [13/171] Generating pixbuf-dpi.test with a custom command
    [14/171] Generating pixbuf-pixdata.test with a custom command
    [15/171] Generating pixbuf-stream.test with a custom command
    [16/171] Generating pixbuf-reftest.test with a custom command
    [17/171] Generating pixbuf-scale.test with a custom command
    [18/171] Generating pixbuf-scale-two-step.test with a custom command
    [19/171] Generating pixbuf-short-gif-write.test with a custom command
    [20/171] Generating pixbuf-resource.test with a custom command
    [21/171] Compiling C object gdk-pixbuf/pixops/timescale.p/timescale.c.o
    [22/171] Generating pixbuf-save.test with a custom command
    [23/171] Generating pixbuf-readonly-to-mutable.test with a custom command
    [24/171] Generating pixbuf-gif-circular-table.test with a custom command
    [25/171] Generating pixbuf-area-updated.test with a custom command
    [26/171] Generating pixbuf-composite.test with a custom command
    [27/171] Generating gdk-pixbuf-enum-types.h with a custom command (wrapped by meson to capture output)
    [28/171] Generating gdk-pixbuf-query-loaders-man with a custom command
    [29/171] Generating gdk-pixbuf-csource-man with a custom command
    [30/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/meson-generated_.._gdk-pixbuf-marshal.c.o
    [31/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-data.c.o
    [32/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-animation.c.o
    [33/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-loader.c.o
    [34/171] Generating gdk-pixbuf-enum-types.c with a custom command (wrapped by meson to capture output)
    [35/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-simple-anim.c.o
    [36/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-scale.c.o
    [37/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/meson-generated_.._gdk-pixbuf-enum-types.c.o
    [38/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf.c.o
    [39/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-util.c.o
    [40/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-scaled-anim.c.o
    [41/171] Compiling C object gdk-pixbuf/pixops/libpixops.a.p/pixops.c.o
    [42/171] Linking static target gdk-pixbuf/pixops/libpixops.a
    [43/171] Linking target gdk-pixbuf/pixops/timescale
    [44/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-io.c.o
    FAILED: gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-io.c.o
    cc -Igdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p -Igdk-pixbuf -I../gdk-pixbuf -I. -I.. -Igdk-pixbuf/pixops -I../gdk-pixbuf/pixops -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=700 -DHAVE_CONFIG_H=1 -g -O2 -ffile-prefix-map=/gdk-pixbuf-2.42.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -Wpointer-arith -Wformat=2 -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wcast-align -Wmissing-noreturn -Wmissing-format-attribute -Wlogical-op -fno-strict-aliasing -Wno-int-conversion -Wno-uninitialized -Wno-discarded-qualifiers -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=empty-body -fvisibility=hidden -DG_LOG_STRUCTURED=1 '-DG_LOG_DOMAIN="GdkPixbuf"' -DGDK_PIXBUF_COMPILATION '-DGDK_PIXBUF_PREFIX="/usr"' '-DGDK_PIXBUF_LOCALEDIR="/usr/share/locale"' '-DGDK_PIXBUF_LIBDIR="/usr/lib/x86_64-linux-gnu"' '-DGDK_PIXBUF_BINARY_VERSION="2.10.0"' -DGDK_PIXBUF_ENABLE_BACKEND '-DPIXBUF_LIBDIR="/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders"' '-DBUILT_MODULES_DIR="/gdk-pixbuf-2.42.2+dfsg/obj-x86_64-linux-gnu/gdk-pixbuf"' -MD -MQ gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-io.c.o -MF gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-io.c.o.d -o gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixbuf-io.c.o -c ../gdk-pixbuf/gdk-pixbuf-io.c
    ../gdk-pixbuf/gdk-pixbuf-io.c: In function ‘gdk_pixbuf_save’:
    ../gdk-pixbuf/gdk-pixbuf-io.c:2508:18: error: implicit declaration of function ‘gdk_pixbuf_savev’; did you mean ‘gdk_pixbuf_save’? [-Werror=implicit-function-declaration]
     2508 |         result = gdk_pixbuf_savev (pixbuf, filename, type,
          |                  ^~~~~~~~~~~~~~~~
          |                  gdk_pixbuf_save
    ../gdk-pixbuf/gdk-pixbuf-io.c:2508:18: warning: nested extern declaration of ‘gdk_pixbuf_savev’ [-Wnested-externs]
    cc1: some warnings being treated as errors
    [45/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/gdk-pixdata.c.o
    [46/171] Compiling C object gdk-pixbuf/libpixbufloader-gif.so.p/io-gif.c.o
    [47/171] Compiling C object gdk-pixbuf/libpixbufloader-gif.so.p/io-gif-animation.c.o
    [48/171] Compiling C object gdk-pixbuf/libpixbufloader-png.so.p/io-png.c.o
    [49/171] Compiling C object gdk-pixbuf/libpixbufloader-bmp.so.p/io-bmp.c.o
    [50/171] Compiling C object gdk-pixbuf/libgdk_pixbuf-2.0.so.0.4200.2.p/pixops_pixops.c.o
    [51/171] Compiling C object gdk-pixbuf/libpixbufloader-ico.so.p/io-ico.c.o
    ninja: build stopped: subcommand failed.
    dh_auto_build: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 ninja -j8 returned exit code 1
    make: *** [debian/rules:15: binary] Error 25
    dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
    debuild: fatal error at line 1182:
    dpkg-buildpackage -us -uc -ui -tc -j8 failed
    Traceback (most recent call last):
      File "<stdin>", line 77, in <module>
      File "<stdin>", line 40, in build
      File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['debuild', '-uc', '-us', '-tc', '-j8']' returned non-zero exit status 29.
    E: run_chroot failed: E: command failed: chroot $1 python3 - < build-gdk-pixbuf-inner.py
    W: listening on child socket failed:
    I: removing tempdir /tmp/mmdebstrap.kvKz0EjypL...
    Traceback (most recent call last):
      File "/home/twb/Desktop/bootstrap2020/debian-11-PrisonPC.packages/./build-gdk-pixbuf.py", line 21, in <module>
        subprocess.check_call(
      File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['mmdebstrap', '--variant=buildd', '--aptopt=Acquire::http::Proxy "http://127.0.0.1:3142"', '--aptopt=Acquire::https::Proxy "DIRECT"', '--dpkgopt=force-unsafe-io', '--dpkgopt=path-exclude=/usr/share/doc/*', '--components=main', '--include=devscripts,libdistro-info-perl,python3,build-essential', '--customize-hook=chroot $1 python3 - < build-gdk-pixbuf-inner.py', '--customize-hook=sync-out /X /tmp/tmpzjm4xy7v', 'bullseye', '/dev/null', '../debian-11.sources']' returned non-zero exit status 1.