D14: sound-juicer (not asunder) for staff CDDA ripping?
<twb> I used to ship "asunder" as a basic "rip a CDDA to Ogg Vorbis" for prison staff.  asunder's not in forky (gtk2) -- https://tracker.debian.org/news/1710051/asunder-removed-from-testing/
<twb> Is there an obvious alternative?
<twb> https://screenshots.debian.net/packages?search=cd+rip only shows other things that are also removed :-)
<twb> I guess plan B is to just say "sorry, we only support DVD ripping now"
<henk> abcde?
<twb> isn't that CLI?
<henk> it is
<twb> has to be GUI; all shells and terminals are banned
<waldi> sound juiocer
<twb> Looks reasonable, let's see if it depends on any libraries I have shitlisted
<twb> haha so guess what, sound-juicer itself is OK, but help:sound-juicer is full of bugs so crashed the install:

    I: running --customize-hook directly: /home/twb/Desktop/bootstrap2020/B20/D14/templates/PrisonPC/hooks/customize70-chromium-not-yelp.py /tmp/mmdebstrap.8o64SF8gGK
    warning: failed to load external entity "/usr/share/help/nl/sound-juicer/legal.xml"
    /usr/share/help/nl/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/nl/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/oc/sound-juicer/legal.xml"
    /usr/share/help/oc/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/oc/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/ar/sound-juicer/legal.xml"
    /usr/share/help/ar/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/ar/sound-juicer/legal.xml, and no fallback was found
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guilabel
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: application
    Unmatched inline element: application
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guilabel
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: application
    Unmatched inline element: application
    warning: failed to load external entity "/usr/share/help/zh_CN/sound-juicer/legal.xml"
    /usr/share/help/zh_CN/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/zh_CN/sound-juicer/legal.xml, and no fallback was found
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guilabel
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: application
    Unmatched inline element: application
    warning: failed to load external entity "/usr/share/help/uk/sound-juicer/legal.xml"
    /usr/share/help/uk/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/uk/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/sv/sound-juicer/legal.xml"
    /usr/share/help/sv/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/sv/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/sl/sound-juicer/legal.xml"
    /usr/share/help/sl/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/sl/sound-juicer/legal.xml, and no fallback was found
    Unmatched inline element: guibutton
    Unmatched inline element: guibutton
    warning: failed to load external entity "/usr/share/help/ru/sound-juicer/legal.xml"
    /usr/share/help/ru/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/ru/sound-juicer/legal.xml, and no fallback was found
    Unmatched inline element: guibutton
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: guibutton
    Unmatched inline element: menuchoice
    Unmatched inline element: guimenu
    Unmatched inline element: guisubmenu
    Unmatched inline element: guimenuitem
    Unmatched inline element: application
    Unmatched inline element: application
    Unmatched inline element: application
    warning: failed to load external entity "/usr/share/help/pt_BR/sound-juicer/legal.xml"
    /usr/share/help/pt_BR/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/pt_BR/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/pl/sound-juicer/legal.xml"
    /usr/share/help/pl/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/pl/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/ja/sound-juicer/legal.xml"
    /usr/share/help/ja/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/ja/sound-juicer/legal.xml, and no fallback was found
    Unmatched inline element: apps
    warning: failed to load external entity "/usr/share/help/fr/sound-juicer/legal.xml"
    /usr/share/help/fr/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/fr/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/eu/sound-juicer/legal.xml"
    /usr/share/help/eu/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/eu/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/es/sound-juicer/legal.xml"
    /usr/share/help/es/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/es/sound-juicer/legal.xml, and no fallback was found
    Unmatched inline element: application
    warning: failed to load external entity "/usr/share/help/en_GB/sound-juicer/legal.xml"
    /usr/share/help/en_GB/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/en_GB/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/el/sound-juicer/legal.xml"
    /usr/share/help/el/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/el/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/de/sound-juicer/legal.xml"
    /usr/share/help/de/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/de/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/cs/sound-juicer/legal.xml"
    /usr/share/help/cs/sound-juicer/./index.docbook:25: element include: XInclude error : could not load /usr/share/help/cs/sound-juicer/legal.xml, and no fallback was found
    Unmatched inline element: guilabel
    Unmatched inline element: application
    warning: failed to load external entity "/usr/share/help/ca/sound-juicer/legal.xml"
    /usr/share/help/ca/sound-juicer/./index.docbook:34: element include: XInclude error : could not load /usr/share/help/ca/sound-juicer/legal.xml, and no fallback was found
    warning: failed to load external entity "/usr/share/help/C/sound-juicer/legal.xml"
    /usr/share/help/C/sound-juicer/./index.docbook:37: element include: XInclude error : could not load /usr/share/help/C/sound-juicer/legal.xml, and no fallback was found
    Traceback (most recent call last):
      File "/home/twb/Desktop/bootstrap2020/B20/D14/templates/PrisonPC/hooks/customize70-chromium-not-yelp.py", line 100, in <module>
        subprocess.check_call([
        ~~~~~~~~~~~~~~~~~~~~~^^
            'chroot', args.chroot_path,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        ...<2 lines>...
            '(', '-name', 'index.docbook', '-execdir', *docbook_command, '{}', '+', ')', ',',
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            '(', '-name', '*.page', '-execdir', *mallard_command, '{}', '+', ')'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.13/subprocess.py", line 419, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['chroot', PosixPath('/tmp/mmdebstrap.8o64SF8gGK'), 'find', '-O3', 'usr/share/help/', '-xdev', '(', '-name', 'index.docbook', '-execdir', 'yelp-build', 'html', '{}', '+', ')', ',', '(', '-name', '*.page', '-execdir', 'yelp-build', 'html', '{}', '+', ')']' returned non-zero exit status 1.
    I: waiting for background processes to finish...