delete-bad-files: remove obsolete numpy kludge
Upstream changes means pygame/numpy do not require "import unittest" at runtime.
Also at least "solarwolf" was playable with unittest gone and without this hack.

root@desktop-staff:~# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import pygame
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> import unittest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'unittest'